### PR TITLE
[2023.09.25.00] Rebuild for glog 0.7

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjerphan** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Thanks for creating the branch and this PR! This doesn't yet change anything but the compiler version; we should include the glog 0.7 migration here, which is what's necessary to unblock https://github.com/conda-forge/arcticdb-feedstock/pull/177.

**Comment by jjerphan** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
This is a job for an interactive rebase. :)

Would be a pity to squash all of that into a single unreadable commit. 🙃

**Comment by jjerphan** [comment]
Should I have integrated changes differently?

**Comment by h-vetinari** [comment]
> Should I have integrated changes differently?

Not pick up all the commits from main, just the ones that are necessary

**Comment by h-vetinari** [comment]
`git rebase -i upstream/2023.09.25.00` and then drop all the unnecessary version bumps and rerenders, plus fix any eventual conflicts (which is partly why I immediately reverted the skip commit before applying the other commits)

**Comment by jjerphan** [comment]
OK, I simply merged `upstream/2023.09.25.00` in this branch.

**Comment by h-vetinari** [comment]
> OK, I simply merged `upstream/2023.09.25.00` in this branch by habits as I did not know whether people have preferences for rebasing (and force-pushing) over merging.

It sounds like you merged `upstream/main`,  because `2023.09.25.00` doesn't have all the version bumps that came along with that merge. Also, since we explicitly branched off at a specific version, we're not force-pushing anything, and so a (selective) rebase of main onto that new branch is the right approach.

From my POV this is good to merge BTW. :)

**Comment by jjerphan** [comment]
> It sounds like you merged `upstream/main`

That's highly possible. I am afraid that I got quite annoyingly numbed with all of madness over the weeks.

**Comment by h-vetinari** [comment]
Sorry to hear it. Hope things are looking up!

**Comment by jjerphan** [comment]
Hello @xhochy,

Could you review this PR? :pray: 

Alternatively, would you trust and allow me to maintain this `2023.09.25.00` branch on my own (merging subsequent pull requests)?

**Review by xhochy — APPROVED** [review]

**Pull request merged**
