### PR TITLE
Support optional jemalloc

### PR DESCRIPTION
**Pull request by pearu**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@conda-forge-admin, please restart ci

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@xhochy Could you review this PR? For some reason, no builds are triggered in this PR. Any ideas?

**Comment by xhochy** [comment]
Looks good, CI is green too: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=365850&view=results

**Comment by pearu** [comment]
Thanks @xhochy !

**Pull request merged**
