### PR TITLE
Create a multioutput recipe to build and distribute shared and static libraries

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jjerphan** [comment]
As observed by @DerThorsten, the Linux builds fail starting https://github.com/conda-forge/folly-feedstock/pull/127/commits/75881a5390461c2e32bc7104f2f4fcbc6b1ba1d1 as `BUILD_PREFIX` is not exported (compare [macOS logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/766096/logs/88) and [linux logs](https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/766096/logs/159) for instance). This likely is a problem with conda-forge's tooling.

**Comment by DerThorsten** [comment]
when adding smth like
```
echo $PREFIX
echo $BUILD_PREFIX
```
it shows that BUILD_PREFIX points to the same dir as PREFIX
 ```
 PREFIX        /home/conda/feedstock_root/build_artifacts/folly_1692691410943/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 BUILD_PREFIX' /home/conda/feedstock_root/build_artifacts/folly_1692691410943/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
 ```

**Comment by DerThorsten** [comment]
maybe @xhochy has an idea what could be going wrong

**Comment by DerThorsten** [comment]
I figured it out, adding a dedicated non-default build script does the trick
```
  # Static library
  - name: folly-static
    script: build_folly.sh   # [unix]
    script: build_folly.bat  # [win]
```

**Comment by jjerphan** [comment]
Closing in favor of #128.

**Pull request closed without merging**
