### PR TITLE
MNT: Re-rendered with conda-build 3.24.0, conda-smithy 3.23.1, and conda-forge-pinning 2023.05.17.11.43.25

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
What is the reason for these PRs? They don't change anything in the build.

**Comment by jjerphan** [comment]
Hi @xhochy, we are trying to package https://github.com/man-group/arcticdb via https://github.com/conda-forge/staged-recipes/pull/22840.

When building the recipe, we get the following errors:

``` 
The reported errors are:
- Encountered problems while solving:
-   - package folly-2022.10.31.00-h1234567_1 requires libevent >=2.1.10,<2.1.11.0a0, but none of the providers can be installed
-   - package aws-sdk-cpp-1.10.57-h19d6a86_1 requires libcurl >=7.87.0,<9.0a0, but none of the providers can be installed
```

E.g. see [this log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=706976&view=logs&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310&l=1113)

We are trying to understand how to resolve it.

**Comment by xhochy** [comment]
The global pinning (actually: the migration) affects the latest release of this feedstock. Old versions are still only build with the old libevent pin. In your error message, it shows an outdated folly version: `folly-2022.10.31.00`. You should pin to the latest release explicitly and then see what the error message is.

**Comment by jjerphan** [comment]
> In your error message, it shows an outdated folly version: `folly-2022.10.31.00`. You should pin to the latest release explicitly and then see what the error message is.

We currently [do not apply constraints on `folly`](https://github.com/conda-forge/staged-recipes/pull/22840/files#diff-8843734caba5b4b8f605f789f233f6d0f9d73389488a715d1353850620f17f47R27) and though a version verifying the constraints would have been used. I will try using the latest release explicitly (or any other that meets the constraints).

**Comment by xhochy** [comment]
The latest build of folly is already should be built against libevent 2.1.12: https://github.com/conda-forge/folly-feedstock/blob/fc1528d25195286807d3f4ff435880e2071c742f/.ci_support/linux_64_fmt9folly_build_extNone.yaml#L26

**Comment by xhochy** [comment]
Having the build number in several places is error-prone and also the bot won't update it automatically on version update PRs. In https://github.com/conda-forge/folly-feedstock/pull/100 I get rid of the duplication

**Comment by jjerphan** [comment]
Closing in favor of https://github.com/conda-forge/folly-feedstock/pull/100.

**Pull request closed without merging**
